apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: staged-deployer
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: This is a system-generated parameter and is required for use in
          application releases. Refer to
          https://docs.cloudbees.com/docs/cloudbees-platform/latest/applications/releases#manifest
          for the expected format
metadata:
  stages/v1alpha1:
    - name: PROD
      jobs:
        - PROD
    - name: QA
      jobs:
        - QA
jobs:
  PROD:
    environment: PROD
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
  QA:
    needs:
      - PROD
    environment: QA
    uses: ./.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: ${{ job.environment }}
